### ISSUE TITLE
Default "STATE" open any folder and just the four toggles your state views or better yet automatic. 

### ISSUE THREAD

**Issue by iDINGUZ** [daledesilva/obsidian_project-browser#13]
ream to click in the folder tree / breadcrumb AND
Get a clean Thumbnails / grid / Card with maximal data / content viewable

**Comment by daledesilva** [comment]
I might need you to explain this a little further as I'm not sure I understand.
Are you saying you've like a way to see a grid of files NOT grouped by state?

**Comment by daledesilva** [comment]
Closing this as I'm unsure what you're describing and haven't heard back. Feel free to reply when you get a chance and I'll reopen if needed.
