### ISSUE TITLE
Add Icons to the mobile toolbar

### ISSUE THREAD

**Issue by paradoxx42** [daledesilva/obsidian_project-browser#16]
**What's your idea?**
I noticed that the mobile toolbar does not have icons, but just (?) placeholders. I think this is a missing feature that‘s crucial to regular usage.
**Why? How would it help you (or others)?**
Is is currently not possible to tell apart multiple functions from Ink like _insert new handwriting_ and _insert new drawing_ on the iPad, where it is most useful imo.
![image](https://github.com/user-attachments/assets/753df95e-323a-4801-9873-cb0946bda711)

**Comment by daledesilva** [comment]
Closing this as it was posted in the wrong project.
It has also been implemented now in Ink.
Thanks for posting!
