### ISSUE TITLE
No continuous input from apple pencil

### ISSUE THREAD

**Issue by GitesHubisz** [daledesilva/obsidian_project-browser#23]
**Describe the bug**

After a hard reset of the tablet and launching the apple pen, the functions of writing as well as drawing do not work. The only thing that the stylus can make are dots. Eraser function works flawlessly with the stylus. It is possible to draw with your finger, but it requires switching to keyboard mode. Touching the stylus against the tablet again blocks the drawing.
I checked basic solutions like reinstalling, restarting obsidian, re-pairing via bluetooth of the stylus did not result in a fix

**Video or screenshots**
https://github.com/user-attachments/assets/8e502101-3c23-450c-b8cc-c8fd4e206f84

**To Reproduce**
If you're video or screenshots need more context, describe the steps reproduce the behavior:
1. Hard reset tablet
2. Open obsidian
3. Open new drawing widget
4. Try to draw

**Expected behavior**
If used to draw a lines.

**Desktop (please complete the following information):**
- **Device & OS**: iOS 18.0.1
- **Plugin version**: 0.2.6
- **Obsidian version**: 1.6.7

**Additional context**
-

**Comment by daledesilva** [comment]
Oh! I'm sorry to hear you're experiencing that.

Can I clarify what a hard reset involves for you? Was it just holding the power button combo and then swiping to confirm?
Or did you wipe the tablet, reinstall?

What was the reason for the hard reset? Did iPadOS update by any chance?

Is it possible that the plug-in update?

Perhaps you could try using the BRAT plug-in and reverting to a specific version of Ink incase that was the cause.

Lastly, does the pen work the same as it used to in other apps like procreate or notes, or in the excalidraw plugin?

**Comment by daledesilva** [comment]
Oh, and one more thing.
I'm pretty sure I've experienced a similar effect before.

I found, in the end, that the tip of the Apple Pencil had become slightly unscrewed. Please try tightening it and hopefully that helps!

**Comment by GitesHubisz** [comment]
As for the update, it was simply that the tablet was discharged. After the reset, this error occurred. I did not install while using the app.


And I was able to fix it. I just forgot that you can do a hard reset again (through settings) and after that it worked. Fortunately, nothing serious happened to the stylus or the system. But I can only theorize that when using apps and the device discharges, such situations can occur again.


Thank you so much for the answer with solutions.

**Comment by GitesHubisz** [comment]
PS: sorry, I mixed up your repos, it should be in Obsidian_ink, but I hope you don't mind it

**Comment by daledesilva** [comment]
Ha ha. I noticed that.
All good mate 👍
