### ISSUE TITLE
Unnecessary blank tabs are opened when pinned tabs are present

### ISSUE THREAD

**Issue by Leolo1** [daledesilva/obsidian_project-browser#4]
Hi - I love your idea and visual implementation of the project browser!

When closing a tab (via [x] in the tab bar or via Ctrl.W) which is located to the immediate right of a pinned tab, a (sometimes great) number of empty tabs open. This also happens when opening a note via the project browser on a pinned tab.

Expected behaviour: The tab closes or is opened respectively and no new tabs are opened.

Reproduction A:
1. Open Obsidian with empty tab showing project browser
2. Pin this tab
3. Open any existing note --> a large number of blank tabs open to the right of the tab

Reproduction B:
1. Open three existing notes
2. Pin middle tab
3. Close rightmost tab --> a large number of blank tabs open to the right of the pinned tab

**Comment by daledesilva** [comment]
Thanks for providing such clear reproduction details. I don't pin tabs much so great you were able to catch it.

I'll jump on this in the next day or so and let you know if I can't reproduce.

**Comment by daledesilva** [comment]
I have definitely reproduced it 😳
I'll get to the bottom of it!

**Comment by Leolo1** [comment]
I work with a daily note as log book for my activities and pin that one to always have it at hand. That's how I noticed the behaviour. Thank you for taking care of it - happy to help with testing if need be. BTW I am impressed with the roadmap you made for the implementation - seems really well thought out. 👍Personally, I would appreciate to have an option to activate the state menu or not as I see notes to always be in an in-progress status.

**Comment by daledesilva** [comment]
Thanks. The ability to enable and disable (and customise) the state menu will definitely be an option. Just getting around to it.

I was actually considering making it its own plug-in. But probably not.

**Comment by daledesilva** [comment]
This is fixed and in the latest update. Thanks for reporting!

**Comment by Leolo1** [comment]
Hi Dale, works like a charm - thank you! 👏

I would support your idea of separating state management from the project browser, as imo an app should solve one problem and that properly. Whoever wants to use state (or whatever other file property) for filtering should be able to do so as I see that indeed to be a valuable feature. But my guess would be that user preferences regarding how to set a file property (via your convenient UI control, the Obsidian-native features or even programatically) will differ. Having your solution as a light-weight extension to manage state which can (but does not have to be) combined with the project browser might be appealing to a lot of users. But that's just me and you should do with your baby whatever the heck you want! Thanks again for your contribution - it's really a great way to navigate the vault (personally am using the PARA approach)!
