### ISSUE TITLE
When binary files are in a vault, this extension causes obsidian to hang

### ISSUE THREAD

**Issue by OliverDudgeon** [daledesilva/obsidian_project-browser#5]
I've noticed when I click into a folder (or at vault root) that contains a binary file (e.g. a pdf), obsidian will hang when this extension is installed. The duration of then hang depends on the size of the file. Is the extension attempting to render a binary file as text? Perhaps it should skip this for non `.md` files?

**Comment by daledesilva** [comment]
Yep. That's exactly what's happening. I hadn't gotten around to handling that but I think what I'll do is just display the title of those files and never consider the contents.

I'll get onto it asap.

**Comment by OliverDudgeon** [comment]
Excellent! Once this is working for me, I think it will be really nice.

**Comment by daledesilva** [comment]
@OliverDudgeon This is now updated. Thanks for posting :)
Just update in your community plugins tab.

Changes documented here:
https://youtube.com/live/517ODVgPxz4
