### ISSUE TITLE
[FR] Could this Plugin be a single page rather than replacing the "New Tab"?

### ISSUE THREAD

**Issue by Moyf** [daledesilva/obsidian_project-browser#6]
Hi! This plugin is so awesome!

And I'm curious that is it possible to open "Project Browser" as a single page (like what Projects did):
![image](https://github.com/daledesilva/obsidian_project-browser/assets/4013062/4d7f7dd3-d2db-4c1e-be8e-633b4426bdfe)

Because I want to use other page for new tab, but still want to use this Browser 🥺

**Comment by daledesilva** [comment]
Sure is. Adding that option is on my list of things to do. Check back in about a week :)

**Comment by Moyf** [comment]
> Sure is. Adding that option is on my list of things to do. Check back in about a week :)

So great!! would wait, thx  <3
