### ISSUE TITLE
Enable searching text into the Project Browser tab

### ISSUE THREAD

**Issue by jockrow** [daledesilva/obsidian_project-browser#9]
Great Plugin.
I suggest this idea:

**Idea?**
Enable searching text into the Project Browser tab

**Why?**
This feature can boosting the workflow meanwhile are searching any title or text in a folder

**Example**
<img width="525" alt="image" src="https://github.com/daledesilva/obsidian_project-browser/assets/30563443/faaa6f5f-f98b-430f-b814-a22597f86c52">

**Comment by daledesilva** [comment]
Thanks. I like the idea of a search 😊

What's the search bar you've screenshotted from? And what to the prev and next buttons do?

**Comment by daledesilva** [comment]
This will be in the next version :) 

You can now filter in Project Browser! - DesDevDiary
https://youtube.com/live/KbQpnr7c-KQ?feature=share
